language: node_js
env:
- NODE_VERSION="5.3"
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq             ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update                         ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full  ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install p7zip                  ;
  fi
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- npm install
before_script:
- export TRAVIS=1
- npm install
script:
- npm run build
before_deploy:
  - export RELEASE_PKG_FILE_OSX=$(ls dist/osx/*.dmg)
  - export RELEASE_PKG_FILE_Linux=$(ls dist/linux/*.7z)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key: "Tl98TtIZUH3LgCVXyEx1rqXa0rHQ/mHpAjnFDKtLZDvImND22a1cGGbbvwb+r1knQokH+MEF4p+PmtoRyQjNQXX6T/keiI/uhG6qo6MWfjZxvSoANvwMO/GWJ2oDjYml5gW9sSZ6nVrw9JySxituujLgVR681Sod40lOKmE5FUg="
  file:
    - "RELEASE_PKG_FILE_OSX"
    - "RELEASE_PKG_FILE_Linux"
  skip_cleanup: true
  on:
    tags: true
