osx_image: xcode7.3

sudo: required
dist: trusty

language: c

node_js:
  - "7"

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 TRAVIS_NODE_VERSION="6"
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - rpm
      - bsdtar

cache:
  directories:
  - node_modules
  - app_compiled/node_modules
  - $HOME/.electron

install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install --silent

before_script:
  - export TRAVIS=1
  - npm install --silent

script:
  - npm run build
  - npm test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+.*/"
